baseURL = 'https://sherises/'
languageCode = 'en-us'
title = 'She Rises'
theme = 'hugo-PaperMod'
[params.homeInfoParams]
Title = "Welcome to She Rises."
Content = "A space for voices, stories, and reflections on feminism and gender equity."

